/**
 * This file was auto-generated by swagger-to-ts.
 * Do not make direct changes to the file.
 */

export interface definitions {
  "data.PublicUser": { created_at?: string; email?: string; id?: string };
  "server.CreateUserRequest": { email?: string; password?: string };
  "server.CreateUserResponse": {
    token?: string;
    user?: definitions["data.PublicUser"];
  };
  "server.ErrorResponse-server_GenericError": {
    error?: definitions["server.GenericError"];
    includes?: { [key: string]: any }[];
    links?: { [key: string]: ref };
    metadata?: { [key: string]: any };
  };
  "server.ErrorResponse-server_HealthcheckResponse": {
    error?: definitions["server.HealthcheckResponse"];
    includes?: { [key: string]: any }[];
    links?: { [key: string]: ref };
    metadata?: { [key: string]: any };
  };
  "server.GenericError": { message?: string };
  "server.GetMessageResponse": { messages?: { [key: string]: any }[] };
  "server.HealthcheckResponse": { healthy?: boolean; status?: number };
  "server.Link": {
    href?: string;
    hreflang?: string;
    link?: definitions["server.Link"];
    meta?: { [key: string]: any };
    rel?: string;
    title?: string;
  };
  "server.SuccessResponse-server_CreateUserResponse": {
    data?: definitions["server.CreateUserResponse"];
    includes?: { [key: string]: any }[];
    links?: { [key: string]: ref };
    metadata?: { [key: string]: any };
  };
  "server.SuccessResponse-server_GetMessageResponse": {
    data?: definitions["server.GetMessageResponse"];
    includes?: { [key: string]: any }[];
    links?: { [key: string]: ref };
    metadata?: { [key: string]: any };
  };
  "server.SuccessResponse-server_HealthcheckResponse": {
    data?: definitions["server.HealthcheckResponse"];
    includes?: { [key: string]: any }[];
    links?: { [key: string]: ref };
    metadata?: { [key: string]: any };
  };
}
